### ISSUE TITLE
SSL routines:SSL_write:protocol is shutdown

### ISSUE THREAD

**Issue by valeriy-efimov** [Live-Rates/live-rates.com#1]
after 10 second work
got error "SSL routines:SSL_write:protocol is shutdown"
![image](https://user-images.githubusercontent.com/5989188/57680623-b47e5300-7636-11e9-83a8-b000f1dc1d56.png)
what could be the problem?
my code

```
$client = new Client(new Version2X('https://wss.live-rates.com/'));
        $client->initialize();
        $client->emit('key', ['key' => '*********']);
        while (true) {
            $r = $client->read();
            var_dump($r);
}
        $client->close();
```

**Comment by acegilz** [comment]
The demo is working fine, I have just tested it now and the sample code you pasted seems fine.
Try cloning the whole repo and run the `php client.php`, it should work.

The backtrace of the error you output is from a path that does not belong to the demo on this repo, you made a manual installation of elephant.io?

**Comment by valerii-efimov** [comment]
@acegilz  yes i made a manual installation of elephant.io
Thanks, I'll try to clone now.

**Comment by acegilz** [comment]
> @acegilz yes i made a manual installation of elephant.io
> Thanks, I'll try to clone now.

Great, please let me know if it works now.

**Comment by valerii-efimov** [comment]
@valeriy-efimov yes your version works. Thank!
now i get new error "Key Already Connected to Streaming Feed.. Disconnected!" But I don't use it anywhere for wss now.

**Comment by valerii-efimov** [comment]
@acegilz   Hi again=) 
I have a problem with your examle
after a couple of hours of work, your example just hangs in place and no longer continues to work. It's like an endless timeout.

`$client->read();`
script work hangs on this line
I ran my script in the supervisor, but due to the fact that here it just hangs up and does not give any errors, the supervisor does not even restart it.


```
        $client = new Client(new Version2X('https://us-wss.live-rates.com/'));
        $client->initialize();
        $client->emit('key', ['key' => env('LIVE_RATES_KEY')]);
        $tries = 0;
        $need_while = true;
        while ($need_while) {
            if($tries>5){
                $need_while = false;
                continue;
            }
            $r = $client->read();
            $array = json_decode($this->getBetween($r,"[","]"));
            $obj = json_decode($array[1]);

            if (!isset($obj->currency)) {
                var_dump($r);
                print("\n");
                $tries++;
            } else {
                $tries = 0;
                echo("Instrument: {$obj->currency} | Ask: {$obj->ask} | Bid: {$obj->bid}");
                print("\n");

            }
        }
        $client->close();
```

![image](https://user-images.githubusercontent.com/5989188/58640456-c6801700-8301-11e9-9ebe-c7b9bd9b3575.png)
Here is an example of the situation.

The script is incomplete and hung on the line
`$r = $client->read();`

**Comment by acegilz** [comment]
"Cloudflare Websocket Proxy Restarting"

Can you connect directly via eu-wss.live-rates.com, or us-wss.live-rates.com and see if the problem persists?

BTW: The nodejs client is much more optimised for socket.io. If you have possibility you may consider switching
